export const ProductListing = [
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM",
    price: "20.50",
    timer: "12d 13h 52 sec",
    bids: "8 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "WOMENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "9.50",
    timer: "1d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$19.60 shipping",
  },
  {
    title: "MENS TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS TITANIUM",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "18.50",
    timer: "6d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
];
export const AuctionsListing = [
  {
    title: "MENS SEIKO KENETIC",
    price: "20.50",
    timer: "1d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "WOMENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "21.50",
    timer: "9d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS TITAN KENETIC TITANIUM 400M WRIST WATCH!",
    price: "20.50",
    timer: "12d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "MENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "41.50",
    timer: "4d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
];
export const BuyNowProducts = [
  {
    title: "MENS SEIKO KENETIC",
    price: "20.50",
    timer: "1d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
  {
    title: "WOMENS SEIKO KENETIC TITANIUM 100M WRIST WATCH! No Reserve!",
    price: "21.50",
    timer: "9d 13h 52 sec",
    bids: "5 bids",
    shipping: "+$11.60 shipping",
  },
];
